// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PencilCase.Telemetry.Data.Database;

#nullable disable

namespace PencilCase.Telemetry.Data.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20241127125548_Table-Create")]
    partial class TableCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PencilCase.Shared.Models.Telemetry.LLM.Agents.GenerationResultEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FinishReason")
                        .HasColumnType("text");

                    b.Property<int>("GenerationCharCount")
                        .HasColumnType("integer");

                    b.Property<int>("GenerationTokenCount")
                        .HasColumnType("integer");

                    b.Property<int>("PromptTokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GenerationResultEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
