// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PencilCase.Telemetry.Data.Database;

#nullable disable

namespace PencilCase.Telemetry.Data.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PencilCase.Shared.Models.Telemetry.LLM.Agents.GenerationResultEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FinishReason")
                        .HasColumnType("text");

                    b.Property<int>("GenerationCharCount")
                        .HasColumnType("integer");

                    b.Property<int>("GenerationTokenCount")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GenerationResultEntries");
                });

            modelBuilder.Entity("PencilCase.Shared.Models.Telemetry.LLM.VectorDb.RagOperationEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<long>("TokensUsed")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitsUsed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RagOperationEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
