// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PencilCase.Shared.Data.Database;

#nullable disable

namespace PencilCase.Shared.Data.Migrations
{
    [DbContext(typeof(BlocksDbContext))]
    [Migration("20250208190654_Block-OwnerId")]
    partial class BlockOwnerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PencilCase.Shared.Models.Notebooks.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Block");
                });

            modelBuilder.Entity("PencilCase.Shared.Models.Notebooks.BlockProperties", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CellShownAnswerId")
                        .HasColumnType("uuid");

                    b.Property<int>("CellType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ParentId");

                    b.ToTable("BlockProperties");
                });

            modelBuilder.Entity("PencilCase.Shared.Models.Notebooks.Block", b =>
                {
                    b.HasOne("PencilCase.Shared.Models.Notebooks.Block", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PencilCase.Shared.Models.Notebooks.BlockProperties", b =>
                {
                    b.HasOne("PencilCase.Shared.Models.Notebooks.Block", "Parent")
                        .WithOne("Properties")
                        .HasForeignKey("PencilCase.Shared.Models.Notebooks.BlockProperties", "ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PencilCase.Shared.Models.Notebooks.Block", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
