name: Deploy

on:
    push:
        branches: ["main"]

    workflow_dispatch:

permissions:
    content: read
    page: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
                uses: actions/checkout@v4
            
            - name: Setup .NET
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 8.0.x
            
            - name: Install .NET WASM tools
                run: dotnet workload install wasm-tools

            - name: Restore Dependencies 
                run: dotnet restore

            - name: Build
                run: dotnet build PencilCase.Web -c Production --no-restore
            
            - name: Publish app
                run: dotnet publish PencilCase.Web -c Production -o docs --no-logo
            
            - name: Setup Pages
                uses: actions/configure-pages@v4

            - name: Upload
                uses: actions/upload-pages-artifact@v3

            - name: Deploy
                id: deployment
                uses: actions/deploy-pages@v4